#!/bin/bash
sudo docker exec autolamp  mysql -uroot -e "CREATE USER ''@'localhost' IDENTIFIED BY '';"
sudo docker exec autolamp  mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO ''@'localhost';"
sudo docker exec autolamp  mysql -uroot -e "create database "
sudo docker exec autolamp  mysql -uroot -e "use ; CREATE TABLE  ("id" int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,  varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL, "fecha" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP);"
echo "El nombre para el usuario es: "
echo "La contraseña para el usuario es: "
echo "El nombre para la base de datos es: "
echo "El nombre para la tabla es: "
echo "El nombre de la variable 1 es : "
echo "Puede entrar a PHPMYADMIN para ver la estructura y canmbiar la configuracion de la base de datos desde el siguiente enlace: http://localhost/phpmyadmin/"
