#!/bin/bash
sudo docker exec autolamp  mysql -uroot -e "CREATE USER 'Ricardo'@'localhost' IDENTIFIED BY '1234';"
sudo docker exec autolamp  mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'Ricardo'@'localhost';"
sudo docker exec autolamp  mysql -uroot -e "create database base323333333333"
sudo docker exec autolamp  mysql -uroot -e "use base323333333333; CREATE TABLE datos ("id" int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,  temp varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL,  rick varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL, hola varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL, zoo varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL,  "fecha" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP);"
echo "El nombre para el usuario es: Ricardo"
echo "La contraseña para el usuario es: 1234"
echo "El nombre para la base de datos es: base323333333333"
echo "El nombre para la tabla es: datos"
echo "El nombre de la variable 1 es : temp"
echo "El nombre de la variable 2 es : rick"
echo "El nombre de la variable 3 es : hola"
echo "El nombre de la variable 4 es : zoo"
echo "Puede entrar a PHPMYADMIN para ver la estructura y canmbiar la configuracion de la base de datos desde el siguiente enlace: http://localhost/phpmyadmin/"
