#!/bin/bash
sudo docker exec autolamp  mysql -uroot -e "CREATE USER 'rick23'@'localhost' IDENTIFIED BY '1234';"
sudo docker exec autolamp  mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'rick23'@'localhost';"
sudo docker exec autolamp  mysql -uroot -e "create database base"
sudo docker exec autolamp  mysql -uroot -e "use base; CREATE TABLE tabla ("id" int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,  temp varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL,  hum varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL,  "fecha" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP);"
echo "El nombre para el usuario es: rick23"
echo "La contraseña para el usuario es: 1234"
echo "El nombre para la base de datos es: base"
echo "El nombre para la tabla es: tabla"
echo "El nombre de la variable 1 es : temp"
echo "El nombre de la variable 2 es : hum"
echo "Puede entrar a PHPMYADMIN para ver la estructura y canmbiar la configuracion de la base de datos desde el siguiente enlace: http://localhost/phpmyadmin/"
