#!/bin/bash
sudo docker exec autolamp  mysql -uroot -e "CREATE USER 'Ricardo'@'localhost' IDENTIFIED BY '1234';"
sudo docker exec autolamp  mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'Ricardo'@'localhost';"
sudo docker exec autolamp  mysql -uroot -e "create database base32"
sudo docker exec autolamp  mysql -uroot -e "use base32; CREATE TABLE tabla ("id" int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,  temp varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL,  asdasd varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL, hola varchar(70) COLLATE utf8mb4_spanish_ci NOT NULL,  "fecha" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP);"
echo "El nombre para el usuario es: Ricardo"
echo "La contraseña para el usuario es: 1234"
echo "El nombre para la base de datos es: base32"
echo "El nombre para la tabla es: tabla"
echo "El nombre de la variable 1 es : temp"
echo "El nombre de la variable 2 es : asdasd"
echo "El nombre de la variable 3 es : hola"
echo "Puede entrar a PHPMYADMIN para ver la estructura y canmbiar la configuracion de la base de datos desde el siguiente enlace: http://localhost/phpmyadmin/"
